registry:
  address: $REGISTRY_HOST

service:
  name: platform.user.srv.passport
  version: v1.0.0
  metadata:
    id: "1"

log:
  path: log
  level: debug
  fileSize: 1024000

mongodb:
  addr:
    - $MONGO_HOST
  username:
  password:
  poolLimit: 10

wechatOpenConfig:
  url: https://api.weixin.qq.com/sns/jscode2session
  secrets:
    wxbff041264334daea: 7c25216a083de795817c10d8b696ad76