// Code generated by protoc-gen-go. DO NOT EDIT.
// source: base.proto

package base

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Code int32

const (
	Code_SUCCEED       Code = 0
	Code_FAILED        Code = 1
	Code_ENCODE_FAILED Code = 2
	Code_DECODE_FAILED Code = 3
)

var Code_name = map[int32]string{
	0: "SUCCEED",
	1: "FAILED",
	2: "ENCODE_FAILED",
	3: "DECODE_FAILED",
}

var Code_value = map[string]int32{
	"SUCCEED":       0,
	"FAILED":        1,
	"ENCODE_FAILED": 2,
	"DECODE_FAILED": 3,
}

func (x Code) String() string {
	return proto.EnumName(Code_name, int32(x))
}

func (Code) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{0}
}

type Resp struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Desc                 string   `protobuf:"bytes,2,opt,name=Desc,proto3" json:"Desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Resp) Reset()         { *m = Resp{} }
func (m *Resp) String() string { return proto.CompactTextString(m) }
func (*Resp) ProtoMessage()    {}
func (*Resp) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{0}
}

func (m *Resp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resp.Unmarshal(m, b)
}
func (m *Resp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resp.Marshal(b, m, deterministic)
}
func (m *Resp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resp.Merge(m, src)
}
func (m *Resp) XXX_Size() int {
	return xxx_messageInfo_Resp.Size(m)
}
func (m *Resp) XXX_DiscardUnknown() {
	xxx_messageInfo_Resp.DiscardUnknown(m)
}

var xxx_messageInfo_Resp proto.InternalMessageInfo

func (m *Resp) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Resp) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func init() {
	proto.RegisterEnum("base.Code", Code_name, Code_value)
	proto.RegisterType((*Resp)(nil), "base.Resp")
}

func init() { proto.RegisterFile("base.proto", fileDescriptor_db1b6b0986796150) }

var fileDescriptor_db1b6b0986796150 = []byte{
	// 134 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x4a, 0x2c, 0x4e,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0x95, 0xf4, 0xb8, 0x58, 0x82, 0x52,
	0x8b, 0x0b, 0x84, 0x84, 0xb8, 0x58, 0x9c, 0xf3, 0x53, 0x52, 0x25, 0x18, 0x15, 0x18, 0x35, 0x78,
	0x83, 0xc0, 0x6c, 0x90, 0x98, 0x4b, 0x6a, 0x71, 0xb2, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x67, 0x10,
	0x98, 0xad, 0xe5, 0x0a, 0x51, 0x27, 0xc4, 0xcd, 0xc5, 0x1e, 0x1c, 0xea, 0xec, 0xec, 0xea, 0xea,
	0x22, 0xc0, 0x20, 0xc4, 0xc5, 0xc5, 0xe6, 0xe6, 0xe8, 0xe9, 0xe3, 0xea, 0x22, 0xc0, 0x28, 0x24,
	0xc8, 0xc5, 0xeb, 0xea, 0xe7, 0xec, 0xef, 0xe2, 0x1a, 0x0f, 0x15, 0x62, 0x02, 0x09, 0xb9, 0xb8,
	0x22, 0x0b, 0x31, 0x27, 0xb1, 0x81, 0xdd, 0x60, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x23, 0x38,
	0x44, 0xa6, 0x91, 0x00, 0x00, 0x00,
}
