// Code generated by protoc-gen-go. DO NOT EDIT.
// source: passport.proto

package platform_user_srv_passport

import (
	fmt "fmt"
	idl "github.com/dy-platform/user-srv-passport/idl"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SignUpReq struct {
	DeviceID             int64    `protobuf:"varint,1,opt,name=DeviceID,proto3" json:"DeviceID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Mobile               string   `protobuf:"bytes,3,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=Email,proto3" json:"Email,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=Password,proto3" json:"Password,omitempty"`
	Code                 string   `protobuf:"bytes,6,opt,name=Code,proto3" json:"Code,omitempty"`
	ActiveType           int32    `protobuf:"varint,7,opt,name=ActiveType,proto3" json:"ActiveType,omitempty"`
	AppID                int32    `protobuf:"varint,8,opt,name=AppID,proto3" json:"AppID,omitempty"`
	Version              string   `protobuf:"bytes,9,opt,name=Version,proto3" json:"Version,omitempty"`
	ExtraInfo            string   `protobuf:"bytes,10,opt,name=ExtraInfo,proto3" json:"ExtraInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUpReq) Reset()         { *m = SignUpReq{} }
func (m *SignUpReq) String() string { return proto.CompactTextString(m) }
func (*SignUpReq) ProtoMessage()    {}
func (*SignUpReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_4affa6d033a78188, []int{0}
}

func (m *SignUpReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpReq.Unmarshal(m, b)
}
func (m *SignUpReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpReq.Marshal(b, m, deterministic)
}
func (m *SignUpReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpReq.Merge(m, src)
}
func (m *SignUpReq) XXX_Size() int {
	return xxx_messageInfo_SignUpReq.Size(m)
}
func (m *SignUpReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpReq.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpReq proto.InternalMessageInfo

func (m *SignUpReq) GetDeviceID() int64 {
	if m != nil {
		return m.DeviceID
	}
	return 0
}

func (m *SignUpReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SignUpReq) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *SignUpReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SignUpReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *SignUpReq) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *SignUpReq) GetActiveType() int32 {
	if m != nil {
		return m.ActiveType
	}
	return 0
}

func (m *SignUpReq) GetAppID() int32 {
	if m != nil {
		return m.AppID
	}
	return 0
}

func (m *SignUpReq) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *SignUpReq) GetExtraInfo() string {
	if m != nil {
		return m.ExtraInfo
	}
	return ""
}

type SignUpResp struct {
	UserID               int64     `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Mobile               string    `protobuf:"bytes,2,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	BaseResp             *idl.Resp `protobuf:"bytes,3,opt,name=BaseResp,proto3" json:"BaseResp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SignUpResp) Reset()         { *m = SignUpResp{} }
func (m *SignUpResp) String() string { return proto.CompactTextString(m) }
func (*SignUpResp) ProtoMessage()    {}
func (*SignUpResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_4affa6d033a78188, []int{1}
}

func (m *SignUpResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpResp.Unmarshal(m, b)
}
func (m *SignUpResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpResp.Marshal(b, m, deterministic)
}
func (m *SignUpResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpResp.Merge(m, src)
}
func (m *SignUpResp) XXX_Size() int {
	return xxx_messageInfo_SignUpResp.Size(m)
}
func (m *SignUpResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpResp.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpResp proto.InternalMessageInfo

func (m *SignUpResp) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *SignUpResp) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *SignUpResp) GetBaseResp() *idl.Resp {
	if m != nil {
		return m.BaseResp
	}
	return nil
}

type MobileSignInReq struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	AppID                int32    `protobuf:"varint,3,opt,name=AppID,proto3" json:"AppID,omitempty"`
	ExtraInfo            string   `protobuf:"bytes,4,opt,name=ExtraInfo,proto3" json:"ExtraInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MobileSignInReq) Reset()         { *m = MobileSignInReq{} }
func (m *MobileSignInReq) String() string { return proto.CompactTextString(m) }
func (*MobileSignInReq) ProtoMessage()    {}
func (*MobileSignInReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_4affa6d033a78188, []int{2}
}

func (m *MobileSignInReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MobileSignInReq.Unmarshal(m, b)
}
func (m *MobileSignInReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MobileSignInReq.Marshal(b, m, deterministic)
}
func (m *MobileSignInReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MobileSignInReq.Merge(m, src)
}
func (m *MobileSignInReq) XXX_Size() int {
	return xxx_messageInfo_MobileSignInReq.Size(m)
}
func (m *MobileSignInReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MobileSignInReq.DiscardUnknown(m)
}

var xxx_messageInfo_MobileSignInReq proto.InternalMessageInfo

func (m *MobileSignInReq) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *MobileSignInReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *MobileSignInReq) GetAppID() int32 {
	if m != nil {
		return m.AppID
	}
	return 0
}

func (m *MobileSignInReq) GetExtraInfo() string {
	if m != nil {
		return m.ExtraInfo
	}
	return ""
}

type MobileSignInResp struct {
	UserID               int64     `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	BaseResp             *idl.Resp `protobuf:"bytes,2,opt,name=BaseResp,proto3" json:"BaseResp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MobileSignInResp) Reset()         { *m = MobileSignInResp{} }
func (m *MobileSignInResp) String() string { return proto.CompactTextString(m) }
func (*MobileSignInResp) ProtoMessage()    {}
func (*MobileSignInResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_4affa6d033a78188, []int{3}
}

func (m *MobileSignInResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MobileSignInResp.Unmarshal(m, b)
}
func (m *MobileSignInResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MobileSignInResp.Marshal(b, m, deterministic)
}
func (m *MobileSignInResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MobileSignInResp.Merge(m, src)
}
func (m *MobileSignInResp) XXX_Size() int {
	return xxx_messageInfo_MobileSignInResp.Size(m)
}
func (m *MobileSignInResp) XXX_DiscardUnknown() {
	xxx_messageInfo_MobileSignInResp.DiscardUnknown(m)
}

var xxx_messageInfo_MobileSignInResp proto.InternalMessageInfo

func (m *MobileSignInResp) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *MobileSignInResp) GetBaseResp() *idl.Resp {
	if m != nil {
		return m.BaseResp
	}
	return nil
}

type EmailSignInReq struct {
	Email                string   `protobuf:"bytes,1,opt,name=Email,proto3" json:"Email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	AppID                int32    `protobuf:"varint,3,opt,name=AppID,proto3" json:"AppID,omitempty"`
	ExtraInfo            string   `protobuf:"bytes,4,opt,name=ExtraInfo,proto3" json:"ExtraInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmailSignInReq) Reset()         { *m = EmailSignInReq{} }
func (m *EmailSignInReq) String() string { return proto.CompactTextString(m) }
func (*EmailSignInReq) ProtoMessage()    {}
func (*EmailSignInReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_4affa6d033a78188, []int{4}
}

func (m *EmailSignInReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailSignInReq.Unmarshal(m, b)
}
func (m *EmailSignInReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailSignInReq.Marshal(b, m, deterministic)
}
func (m *EmailSignInReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailSignInReq.Merge(m, src)
}
func (m *EmailSignInReq) XXX_Size() int {
	return xxx_messageInfo_EmailSignInReq.Size(m)
}
func (m *EmailSignInReq) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailSignInReq.DiscardUnknown(m)
}

var xxx_messageInfo_EmailSignInReq proto.InternalMessageInfo

func (m *EmailSignInReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *EmailSignInReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *EmailSignInReq) GetAppID() int32 {
	if m != nil {
		return m.AppID
	}
	return 0
}

func (m *EmailSignInReq) GetExtraInfo() string {
	if m != nil {
		return m.ExtraInfo
	}
	return ""
}

type EmailSignInResp struct {
	UserID               int64     `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	BaseResp             *idl.Resp `protobuf:"bytes,2,opt,name=BaseResp,proto3" json:"BaseResp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *EmailSignInResp) Reset()         { *m = EmailSignInResp{} }
func (m *EmailSignInResp) String() string { return proto.CompactTextString(m) }
func (*EmailSignInResp) ProtoMessage()    {}
func (*EmailSignInResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_4affa6d033a78188, []int{5}
}

func (m *EmailSignInResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailSignInResp.Unmarshal(m, b)
}
func (m *EmailSignInResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailSignInResp.Marshal(b, m, deterministic)
}
func (m *EmailSignInResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailSignInResp.Merge(m, src)
}
func (m *EmailSignInResp) XXX_Size() int {
	return xxx_messageInfo_EmailSignInResp.Size(m)
}
func (m *EmailSignInResp) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailSignInResp.DiscardUnknown(m)
}

var xxx_messageInfo_EmailSignInResp proto.InternalMessageInfo

func (m *EmailSignInResp) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *EmailSignInResp) GetBaseResp() *idl.Resp {
	if m != nil {
		return m.BaseResp
	}
	return nil
}

type UserNameSignInReq struct {
	UserName             string   `protobuf:"bytes,1,opt,name=UserName,proto3" json:"UserName,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	AppID                int32    `protobuf:"varint,3,opt,name=AppID,proto3" json:"AppID,omitempty"`
	ExtraInfo            string   `protobuf:"bytes,4,opt,name=ExtraInfo,proto3" json:"ExtraInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserNameSignInReq) Reset()         { *m = UserNameSignInReq{} }
func (m *UserNameSignInReq) String() string { return proto.CompactTextString(m) }
func (*UserNameSignInReq) ProtoMessage()    {}
func (*UserNameSignInReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_4affa6d033a78188, []int{6}
}

func (m *UserNameSignInReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserNameSignInReq.Unmarshal(m, b)
}
func (m *UserNameSignInReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserNameSignInReq.Marshal(b, m, deterministic)
}
func (m *UserNameSignInReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserNameSignInReq.Merge(m, src)
}
func (m *UserNameSignInReq) XXX_Size() int {
	return xxx_messageInfo_UserNameSignInReq.Size(m)
}
func (m *UserNameSignInReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserNameSignInReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserNameSignInReq proto.InternalMessageInfo

func (m *UserNameSignInReq) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserNameSignInReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserNameSignInReq) GetAppID() int32 {
	if m != nil {
		return m.AppID
	}
	return 0
}

func (m *UserNameSignInReq) GetExtraInfo() string {
	if m != nil {
		return m.ExtraInfo
	}
	return ""
}

type UserNameSignInResp struct {
	UserID               int64     `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	BaseResp             *idl.Resp `protobuf:"bytes,2,opt,name=BaseResp,proto3" json:"BaseResp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UserNameSignInResp) Reset()         { *m = UserNameSignInResp{} }
func (m *UserNameSignInResp) String() string { return proto.CompactTextString(m) }
func (*UserNameSignInResp) ProtoMessage()    {}
func (*UserNameSignInResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_4affa6d033a78188, []int{7}
}

func (m *UserNameSignInResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserNameSignInResp.Unmarshal(m, b)
}
func (m *UserNameSignInResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserNameSignInResp.Marshal(b, m, deterministic)
}
func (m *UserNameSignInResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserNameSignInResp.Merge(m, src)
}
func (m *UserNameSignInResp) XXX_Size() int {
	return xxx_messageInfo_UserNameSignInResp.Size(m)
}
func (m *UserNameSignInResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UserNameSignInResp.DiscardUnknown(m)
}

var xxx_messageInfo_UserNameSignInResp proto.InternalMessageInfo

func (m *UserNameSignInResp) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *UserNameSignInResp) GetBaseResp() *idl.Resp {
	if m != nil {
		return m.BaseResp
	}
	return nil
}

type TokenSignInReq struct {
	DeviceID             int64    `protobuf:"varint,1,opt,name=DeviceID,proto3" json:"DeviceID,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=Token,proto3" json:"Token,omitempty"`
	Mobile               string   `protobuf:"bytes,3,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	AppID                int32    `protobuf:"varint,4,opt,name=AppID,proto3" json:"AppID,omitempty"`
	ExtraInfo            string   `protobuf:"bytes,5,opt,name=ExtraInfo,proto3" json:"ExtraInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenSignInReq) Reset()         { *m = TokenSignInReq{} }
func (m *TokenSignInReq) String() string { return proto.CompactTextString(m) }
func (*TokenSignInReq) ProtoMessage()    {}
func (*TokenSignInReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_4affa6d033a78188, []int{8}
}

func (m *TokenSignInReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenSignInReq.Unmarshal(m, b)
}
func (m *TokenSignInReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenSignInReq.Marshal(b, m, deterministic)
}
func (m *TokenSignInReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenSignInReq.Merge(m, src)
}
func (m *TokenSignInReq) XXX_Size() int {
	return xxx_messageInfo_TokenSignInReq.Size(m)
}
func (m *TokenSignInReq) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenSignInReq.DiscardUnknown(m)
}

var xxx_messageInfo_TokenSignInReq proto.InternalMessageInfo

func (m *TokenSignInReq) GetDeviceID() int64 {
	if m != nil {
		return m.DeviceID
	}
	return 0
}

func (m *TokenSignInReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *TokenSignInReq) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *TokenSignInReq) GetAppID() int32 {
	if m != nil {
		return m.AppID
	}
	return 0
}

func (m *TokenSignInReq) GetExtraInfo() string {
	if m != nil {
		return m.ExtraInfo
	}
	return ""
}

type TokenSignInResp struct {
	UserID               int64     `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	BaseResp             *idl.Resp `protobuf:"bytes,2,opt,name=BaseResp,proto3" json:"BaseResp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *TokenSignInResp) Reset()         { *m = TokenSignInResp{} }
func (m *TokenSignInResp) String() string { return proto.CompactTextString(m) }
func (*TokenSignInResp) ProtoMessage()    {}
func (*TokenSignInResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_4affa6d033a78188, []int{9}
}

func (m *TokenSignInResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenSignInResp.Unmarshal(m, b)
}
func (m *TokenSignInResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenSignInResp.Marshal(b, m, deterministic)
}
func (m *TokenSignInResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenSignInResp.Merge(m, src)
}
func (m *TokenSignInResp) XXX_Size() int {
	return xxx_messageInfo_TokenSignInResp.Size(m)
}
func (m *TokenSignInResp) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenSignInResp.DiscardUnknown(m)
}

var xxx_messageInfo_TokenSignInResp proto.InternalMessageInfo

func (m *TokenSignInResp) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *TokenSignInResp) GetBaseResp() *idl.Resp {
	if m != nil {
		return m.BaseResp
	}
	return nil
}

type SignOutReq struct {
	UserID               int64    `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignOutReq) Reset()         { *m = SignOutReq{} }
func (m *SignOutReq) String() string { return proto.CompactTextString(m) }
func (*SignOutReq) ProtoMessage()    {}
func (*SignOutReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_4affa6d033a78188, []int{10}
}

func (m *SignOutReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignOutReq.Unmarshal(m, b)
}
func (m *SignOutReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignOutReq.Marshal(b, m, deterministic)
}
func (m *SignOutReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignOutReq.Merge(m, src)
}
func (m *SignOutReq) XXX_Size() int {
	return xxx_messageInfo_SignOutReq.Size(m)
}
func (m *SignOutReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SignOutReq.DiscardUnknown(m)
}

var xxx_messageInfo_SignOutReq proto.InternalMessageInfo

func (m *SignOutReq) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type SignOutResp struct {
	BaseResp             *idl.Resp `protobuf:"bytes,1,opt,name=BaseResp,proto3" json:"BaseResp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SignOutResp) Reset()         { *m = SignOutResp{} }
func (m *SignOutResp) String() string { return proto.CompactTextString(m) }
func (*SignOutResp) ProtoMessage()    {}
func (*SignOutResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_4affa6d033a78188, []int{11}
}

func (m *SignOutResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignOutResp.Unmarshal(m, b)
}
func (m *SignOutResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignOutResp.Marshal(b, m, deterministic)
}
func (m *SignOutResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignOutResp.Merge(m, src)
}
func (m *SignOutResp) XXX_Size() int {
	return xxx_messageInfo_SignOutResp.Size(m)
}
func (m *SignOutResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SignOutResp.DiscardUnknown(m)
}

var xxx_messageInfo_SignOutResp proto.InternalMessageInfo

func (m *SignOutResp) GetBaseResp() *idl.Resp {
	if m != nil {
		return m.BaseResp
	}
	return nil
}

type ChangePasswordReq struct {
	UserID               int64    `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	AppID                int32    `protobuf:"varint,2,opt,name=AppID,proto3" json:"AppID,omitempty"`
	OldPassword          string   `protobuf:"bytes,3,opt,name=OldPassword,proto3" json:"OldPassword,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=Password,proto3" json:"Password,omitempty"`
	ExtraInfo            string   `protobuf:"bytes,5,opt,name=ExtraInfo,proto3" json:"ExtraInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangePasswordReq) Reset()         { *m = ChangePasswordReq{} }
func (m *ChangePasswordReq) String() string { return proto.CompactTextString(m) }
func (*ChangePasswordReq) ProtoMessage()    {}
func (*ChangePasswordReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_4affa6d033a78188, []int{12}
}

func (m *ChangePasswordReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePasswordReq.Unmarshal(m, b)
}
func (m *ChangePasswordReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePasswordReq.Marshal(b, m, deterministic)
}
func (m *ChangePasswordReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePasswordReq.Merge(m, src)
}
func (m *ChangePasswordReq) XXX_Size() int {
	return xxx_messageInfo_ChangePasswordReq.Size(m)
}
func (m *ChangePasswordReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePasswordReq.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePasswordReq proto.InternalMessageInfo

func (m *ChangePasswordReq) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *ChangePasswordReq) GetAppID() int32 {
	if m != nil {
		return m.AppID
	}
	return 0
}

func (m *ChangePasswordReq) GetOldPassword() string {
	if m != nil {
		return m.OldPassword
	}
	return ""
}

func (m *ChangePasswordReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *ChangePasswordReq) GetExtraInfo() string {
	if m != nil {
		return m.ExtraInfo
	}
	return ""
}

type ChangePasswordResp struct {
	BaseResp             *idl.Resp `protobuf:"bytes,1,opt,name=BaseResp,proto3" json:"BaseResp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ChangePasswordResp) Reset()         { *m = ChangePasswordResp{} }
func (m *ChangePasswordResp) String() string { return proto.CompactTextString(m) }
func (*ChangePasswordResp) ProtoMessage()    {}
func (*ChangePasswordResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_4affa6d033a78188, []int{13}
}

func (m *ChangePasswordResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePasswordResp.Unmarshal(m, b)
}
func (m *ChangePasswordResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePasswordResp.Marshal(b, m, deterministic)
}
func (m *ChangePasswordResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePasswordResp.Merge(m, src)
}
func (m *ChangePasswordResp) XXX_Size() int {
	return xxx_messageInfo_ChangePasswordResp.Size(m)
}
func (m *ChangePasswordResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePasswordResp.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePasswordResp proto.InternalMessageInfo

func (m *ChangePasswordResp) GetBaseResp() *idl.Resp {
	if m != nil {
		return m.BaseResp
	}
	return nil
}

type ResetPasswordReq struct {
	UserID               int64    `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	AppID                int32    `protobuf:"varint,2,opt,name=AppID,proto3" json:"AppID,omitempty"`
	Mobile               string   `protobuf:"bytes,3,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	Code                 string   `protobuf:"bytes,4,opt,name=Code,proto3" json:"Code,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=Password,proto3" json:"Password,omitempty"`
	ExtraInfo            string   `protobuf:"bytes,6,opt,name=ExtraInfo,proto3" json:"ExtraInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetPasswordReq) Reset()         { *m = ResetPasswordReq{} }
func (m *ResetPasswordReq) String() string { return proto.CompactTextString(m) }
func (*ResetPasswordReq) ProtoMessage()    {}
func (*ResetPasswordReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_4affa6d033a78188, []int{14}
}

func (m *ResetPasswordReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetPasswordReq.Unmarshal(m, b)
}
func (m *ResetPasswordReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetPasswordReq.Marshal(b, m, deterministic)
}
func (m *ResetPasswordReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetPasswordReq.Merge(m, src)
}
func (m *ResetPasswordReq) XXX_Size() int {
	return xxx_messageInfo_ResetPasswordReq.Size(m)
}
func (m *ResetPasswordReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetPasswordReq.DiscardUnknown(m)
}

var xxx_messageInfo_ResetPasswordReq proto.InternalMessageInfo

func (m *ResetPasswordReq) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *ResetPasswordReq) GetAppID() int32 {
	if m != nil {
		return m.AppID
	}
	return 0
}

func (m *ResetPasswordReq) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *ResetPasswordReq) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *ResetPasswordReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *ResetPasswordReq) GetExtraInfo() string {
	if m != nil {
		return m.ExtraInfo
	}
	return ""
}

type ResetPasswordResp struct {
	UserID               int64     `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Mobile               string    `protobuf:"bytes,2,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	BaseResp             *idl.Resp `protobuf:"bytes,3,opt,name=BaseResp,proto3" json:"BaseResp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ResetPasswordResp) Reset()         { *m = ResetPasswordResp{} }
func (m *ResetPasswordResp) String() string { return proto.CompactTextString(m) }
func (*ResetPasswordResp) ProtoMessage()    {}
func (*ResetPasswordResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_4affa6d033a78188, []int{15}
}

func (m *ResetPasswordResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetPasswordResp.Unmarshal(m, b)
}
func (m *ResetPasswordResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetPasswordResp.Marshal(b, m, deterministic)
}
func (m *ResetPasswordResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetPasswordResp.Merge(m, src)
}
func (m *ResetPasswordResp) XXX_Size() int {
	return xxx_messageInfo_ResetPasswordResp.Size(m)
}
func (m *ResetPasswordResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetPasswordResp.DiscardUnknown(m)
}

var xxx_messageInfo_ResetPasswordResp proto.InternalMessageInfo

func (m *ResetPasswordResp) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *ResetPasswordResp) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *ResetPasswordResp) GetBaseResp() *idl.Resp {
	if m != nil {
		return m.BaseResp
	}
	return nil
}

type BindMobileReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BindMobileReq) Reset()         { *m = BindMobileReq{} }
func (m *BindMobileReq) String() string { return proto.CompactTextString(m) }
func (*BindMobileReq) ProtoMessage()    {}
func (*BindMobileReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_4affa6d033a78188, []int{16}
}

func (m *BindMobileReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BindMobileReq.Unmarshal(m, b)
}
func (m *BindMobileReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BindMobileReq.Marshal(b, m, deterministic)
}
func (m *BindMobileReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BindMobileReq.Merge(m, src)
}
func (m *BindMobileReq) XXX_Size() int {
	return xxx_messageInfo_BindMobileReq.Size(m)
}
func (m *BindMobileReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BindMobileReq.DiscardUnknown(m)
}

var xxx_messageInfo_BindMobileReq proto.InternalMessageInfo

type BindMobileResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BindMobileResp) Reset()         { *m = BindMobileResp{} }
func (m *BindMobileResp) String() string { return proto.CompactTextString(m) }
func (*BindMobileResp) ProtoMessage()    {}
func (*BindMobileResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_4affa6d033a78188, []int{17}
}

func (m *BindMobileResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BindMobileResp.Unmarshal(m, b)
}
func (m *BindMobileResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BindMobileResp.Marshal(b, m, deterministic)
}
func (m *BindMobileResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BindMobileResp.Merge(m, src)
}
func (m *BindMobileResp) XXX_Size() int {
	return xxx_messageInfo_BindMobileResp.Size(m)
}
func (m *BindMobileResp) XXX_DiscardUnknown() {
	xxx_messageInfo_BindMobileResp.DiscardUnknown(m)
}

var xxx_messageInfo_BindMobileResp proto.InternalMessageInfo

type UnbindMobileReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnbindMobileReq) Reset()         { *m = UnbindMobileReq{} }
func (m *UnbindMobileReq) String() string { return proto.CompactTextString(m) }
func (*UnbindMobileReq) ProtoMessage()    {}
func (*UnbindMobileReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_4affa6d033a78188, []int{18}
}

func (m *UnbindMobileReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnbindMobileReq.Unmarshal(m, b)
}
func (m *UnbindMobileReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnbindMobileReq.Marshal(b, m, deterministic)
}
func (m *UnbindMobileReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnbindMobileReq.Merge(m, src)
}
func (m *UnbindMobileReq) XXX_Size() int {
	return xxx_messageInfo_UnbindMobileReq.Size(m)
}
func (m *UnbindMobileReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UnbindMobileReq.DiscardUnknown(m)
}

var xxx_messageInfo_UnbindMobileReq proto.InternalMessageInfo

type UnbindMobileResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnbindMobileResp) Reset()         { *m = UnbindMobileResp{} }
func (m *UnbindMobileResp) String() string { return proto.CompactTextString(m) }
func (*UnbindMobileResp) ProtoMessage()    {}
func (*UnbindMobileResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_4affa6d033a78188, []int{19}
}

func (m *UnbindMobileResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnbindMobileResp.Unmarshal(m, b)
}
func (m *UnbindMobileResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnbindMobileResp.Marshal(b, m, deterministic)
}
func (m *UnbindMobileResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnbindMobileResp.Merge(m, src)
}
func (m *UnbindMobileResp) XXX_Size() int {
	return xxx_messageInfo_UnbindMobileResp.Size(m)
}
func (m *UnbindMobileResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UnbindMobileResp.DiscardUnknown(m)
}

var xxx_messageInfo_UnbindMobileResp proto.InternalMessageInfo

func init() {
	proto.RegisterType((*SignUpReq)(nil), "platform.user.srv.passport.SignUpReq")
	proto.RegisterType((*SignUpResp)(nil), "platform.user.srv.passport.SignUpResp")
	proto.RegisterType((*MobileSignInReq)(nil), "platform.user.srv.passport.MobileSignInReq")
	proto.RegisterType((*MobileSignInResp)(nil), "platform.user.srv.passport.MobileSignInResp")
	proto.RegisterType((*EmailSignInReq)(nil), "platform.user.srv.passport.EmailSignInReq")
	proto.RegisterType((*EmailSignInResp)(nil), "platform.user.srv.passport.EmailSignInResp")
	proto.RegisterType((*UserNameSignInReq)(nil), "platform.user.srv.passport.UserNameSignInReq")
	proto.RegisterType((*UserNameSignInResp)(nil), "platform.user.srv.passport.UserNameSignInResp")
	proto.RegisterType((*TokenSignInReq)(nil), "platform.user.srv.passport.TokenSignInReq")
	proto.RegisterType((*TokenSignInResp)(nil), "platform.user.srv.passport.TokenSignInResp")
	proto.RegisterType((*SignOutReq)(nil), "platform.user.srv.passport.SignOutReq")
	proto.RegisterType((*SignOutResp)(nil), "platform.user.srv.passport.SignOutResp")
	proto.RegisterType((*ChangePasswordReq)(nil), "platform.user.srv.passport.ChangePasswordReq")
	proto.RegisterType((*ChangePasswordResp)(nil), "platform.user.srv.passport.ChangePasswordResp")
	proto.RegisterType((*ResetPasswordReq)(nil), "platform.user.srv.passport.ResetPasswordReq")
	proto.RegisterType((*ResetPasswordResp)(nil), "platform.user.srv.passport.ResetPasswordResp")
	proto.RegisterType((*BindMobileReq)(nil), "platform.user.srv.passport.BindMobileReq")
	proto.RegisterType((*BindMobileResp)(nil), "platform.user.srv.passport.BindMobileResp")
	proto.RegisterType((*UnbindMobileReq)(nil), "platform.user.srv.passport.UnbindMobileReq")
	proto.RegisterType((*UnbindMobileResp)(nil), "platform.user.srv.passport.UnbindMobileResp")
}

func init() { proto.RegisterFile("passport.proto", fileDescriptor_4affa6d033a78188) }

var fileDescriptor_4affa6d033a78188 = []byte{
	// 726 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x96, 0x4d, 0x6f, 0x13, 0x3d,
	0x10, 0xc7, 0xb5, 0x69, 0x92, 0x26, 0x93, 0xa7, 0x79, 0x19, 0x55, 0x8f, 0x56, 0x2b, 0x84, 0xa2,
	0x08, 0x4a, 0x69, 0xe9, 0x1e, 0x8a, 0xb8, 0x71, 0xe9, 0xdb, 0x21, 0x07, 0x28, 0x2c, 0x2d, 0x48,
	0xdc, 0x36, 0x8d, 0x5b, 0x56, 0x4d, 0x77, 0xdd, 0xf5, 0x36, 0xd0, 0x13, 0x47, 0x6e, 0x7c, 0x00,
	0x24, 0xae, 0x7c, 0x4e, 0x64, 0x3b, 0xd9, 0xb5, 0xdd, 0xc6, 0x24, 0x28, 0xdc, 0x32, 0xb3, 0x33,
	0x63, 0xff, 0xc6, 0x9e, 0xbf, 0x03, 0x4d, 0x1a, 0x32, 0x46, 0x93, 0x34, 0xf3, 0x69, 0x9a, 0x64,
	0x09, 0x7a, 0x74, 0x14, 0x66, 0xe7, 0x49, 0x7a, 0xe5, 0xdf, 0x30, 0x92, 0xfa, 0x2c, 0x1d, 0xfb,
	0xd3, 0x08, 0x0f, 0x06, 0x21, 0x23, 0x32, 0xae, 0xf7, 0xad, 0x04, 0xf5, 0x77, 0xd1, 0x45, 0x7c,
	0x4a, 0x03, 0x72, 0x8d, 0x1e, 0xd4, 0x0e, 0xc9, 0x38, 0x3a, 0x23, 0xfd, 0x43, 0xd7, 0xe9, 0x3a,
	0x9b, 0x2b, 0x41, 0x6e, 0x23, 0x42, 0xf9, 0x75, 0x78, 0x45, 0xdc, 0x52, 0xd7, 0xd9, 0xac, 0x07,
	0xe2, 0x37, 0xfe, 0x0f, 0xd5, 0x57, 0xc9, 0x20, 0x1a, 0x11, 0x77, 0x45, 0x78, 0x27, 0x16, 0xae,
	0x43, 0xe5, 0xe8, 0x2a, 0x8c, 0x46, 0x6e, 0x59, 0xb8, 0xa5, 0xc1, 0xab, 0xbf, 0x09, 0x19, 0xfb,
	0x9c, 0xa4, 0x43, 0xb7, 0x22, 0x3e, 0xe4, 0x36, 0xaf, 0x7e, 0x90, 0x0c, 0x89, 0x5b, 0x95, 0xd5,
	0xf9, 0x6f, 0x7c, 0x08, 0xb0, 0x77, 0x96, 0x45, 0x63, 0x72, 0x72, 0x4b, 0x89, 0xbb, 0xda, 0x75,
	0x36, 0x2b, 0x81, 0xe2, 0xe1, 0xab, 0xec, 0x51, 0xda, 0x3f, 0x74, 0x6b, 0xe2, 0x93, 0x34, 0xd0,
	0x85, 0xd5, 0xf7, 0x24, 0x65, 0x51, 0x12, 0xbb, 0x75, 0x51, 0x6c, 0x6a, 0xe2, 0x03, 0xa8, 0x1f,
	0x7d, 0xc9, 0xd2, 0xb0, 0x1f, 0x9f, 0x27, 0x2e, 0x88, 0x6f, 0x85, 0xa3, 0x37, 0x04, 0x98, 0x36,
	0x82, 0x51, 0x4e, 0x76, 0xca, 0x48, 0x9a, 0xf7, 0x61, 0x62, 0x29, 0xc4, 0x25, 0x8d, 0x78, 0x03,
	0x6a, 0xfb, 0x21, 0x23, 0x3c, 0x57, 0xf4, 0xa2, 0xb1, 0x0b, 0xbe, 0x68, 0x33, 0xf7, 0x04, 0xf9,
	0xb7, 0xde, 0x2d, 0xb4, 0x64, 0x06, 0x5f, 0xab, 0x1f, 0xf3, 0xa6, 0x17, 0x25, 0x1d, 0xad, 0xa4,
	0xda, 0xae, 0x92, 0xd1, 0xae, 0x1c, 0x7d, 0x45, 0x45, 0xd7, 0x00, 0xcb, 0x26, 0x60, 0x00, 0x6d,
	0x7d, 0x69, 0x0b, 0xa6, 0x8a, 0x53, 0xb2, 0xe0, 0x8c, 0xa1, 0x29, 0xce, 0xb6, 0xa0, 0xc9, 0x8f,
	0xde, 0x99, 0x75, 0xf4, 0xcb, 0x60, 0x79, 0x0b, 0x2d, 0x6d, 0xdd, 0x25, 0xa0, 0x7c, 0x85, 0x0e,
	0xcf, 0xe0, 0xf7, 0xba, 0xa0, 0xf1, 0xa0, 0x36, 0x75, 0x4e, 0x80, 0x72, 0x7b, 0xe9, 0x4c, 0x27,
	0x80, 0xe6, 0x06, 0x96, 0x80, 0xf5, 0xdd, 0x81, 0xe6, 0x49, 0x72, 0x49, 0x62, 0x0d, 0x6a, 0xe6,
	0x94, 0xaf, 0x43, 0x45, 0x44, 0x4f, 0x88, 0xa4, 0x61, 0x9b, 0x73, 0x89, 0x59, 0x9e, 0x89, 0x59,
	0xb9, 0xe7, 0xe8, 0xb4, 0xfd, 0x2c, 0x81, 0xf1, 0x91, 0x1c, 0xdd, 0xe3, 0x9b, 0x6c, 0x32, 0x4f,
	0xf7, 0x55, 0xeb, 0xbd, 0x80, 0x46, 0x1e, 0xc5, 0xa8, 0x56, 0xdc, 0xb1, 0x14, 0xff, 0xe9, 0x40,
	0xe7, 0xe0, 0x53, 0x18, 0x5f, 0x90, 0xe9, 0xe9, 0x5a, 0x16, 0x29, 0x3a, 0x52, 0x52, 0x3b, 0xd2,
	0x85, 0xc6, 0xf1, 0x68, 0x98, 0xdf, 0x16, 0xd9, 0x44, 0xd5, 0xa5, 0x5d, 0xa6, 0xb2, 0x71, 0x99,
	0xec, 0xfd, 0x7c, 0x09, 0x68, 0x6e, 0x6f, 0x01, 0xba, 0x5f, 0x0e, 0xb4, 0x03, 0xc2, 0x48, 0xf6,
	0xf7, 0x70, 0xb3, 0x2e, 0xc7, 0x54, 0xd2, 0xcb, 0x8a, 0xa4, 0xdb, 0x9e, 0x00, 0x0d, 0xb3, 0x6a,
	0x62, 0x5e, 0x42, 0xc7, 0xd8, 0xe7, 0x3f, 0x54, 0xe9, 0x16, 0xac, 0xed, 0x47, 0xf1, 0x50, 0x66,
	0x05, 0xe4, 0xba, 0xd7, 0x86, 0xa6, 0xea, 0x60, 0xb4, 0xd7, 0x81, 0xd6, 0x69, 0x3c, 0xd0, 0x82,
	0x10, 0xda, 0xba, 0x8b, 0xd1, 0xdd, 0x1f, 0x35, 0x49, 0xcc, 0x1f, 0x5e, 0xfc, 0x00, 0x55, 0xf9,
	0xc4, 0xe0, 0x63, 0x7f, 0xf6, 0xfb, 0xec, 0xe7, 0xef, 0xb1, 0xb7, 0x31, 0x4f, 0x18, 0xa3, 0x18,
	0xc1, 0x7f, 0xaa, 0xb4, 0xe3, 0xb6, 0x2d, 0xcf, 0x78, 0x7f, 0xbc, 0x67, 0xf3, 0x07, 0x33, 0x8a,
	0xe7, 0xd0, 0x50, 0x94, 0x17, 0xb7, 0x6c, 0xc9, 0xfa, 0xd3, 0xe0, 0x6d, 0xcf, 0x1d, 0xcb, 0x28,
	0x26, 0xd0, 0xd4, 0xd5, 0x10, 0x77, 0x6c, 0xe9, 0x77, 0xa4, 0xdb, 0xf3, 0x17, 0x09, 0x97, 0x60,
	0x8a, 0x2e, 0xd9, 0xc1, 0x74, 0x41, 0xb5, 0x83, 0x99, 0x62, 0xf7, 0x11, 0x56, 0x27, 0x32, 0x84,
	0x7f, 0x3c, 0x5e, 0xa9, 0x68, 0xde, 0x93, 0xb9, 0xe2, 0x64, 0xd3, 0x74, 0x2d, 0xb0, 0x37, 0xed,
	0x8e, 0xac, 0xd9, 0x9b, 0x76, 0x8f, 0xcc, 0x8c, 0x60, 0x4d, 0x9b, 0x4a, 0xb4, 0x5e, 0x26, 0x53,
	0x68, 0xbc, 0x9d, 0x05, 0xa2, 0x19, 0xc5, 0x33, 0x80, 0x62, 0x0a, 0xf1, 0xa9, 0x2d, 0x59, 0x1b,
	0x5f, 0x6f, 0x6b, 0xde, 0x50, 0x39, 0x4b, 0xea, 0x14, 0xdb, 0x67, 0xc9, 0x90, 0x00, 0xfb, 0x2c,
	0x99, 0xe2, 0x30, 0xa8, 0x8a, 0xff, 0xe0, 0xcf, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0x0e, 0x69,
	0xfb, 0x5f, 0xbd, 0x0b, 0x00, 0x00,
}
