// Code generated by protoc-gen-go. DO NOT EDIT.
// source: base.proto

package base

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CODE int32

const (
	CODE_OK                CODE = 0
	CODE_FAILED            CODE = 1
	CODE_ENCODE_FAILED     CODE = 2
	CODE_DECODE_FAILED     CODE = 3
	CODE_SERVICE_EXCEPTION CODE = 4
	CODE_DATA_EXCEPTION    CODE = 10
	CODE_INVALID_PARAMETER CODE = 11
)

var CODE_name = map[int32]string{
	0:  "OK",
	1:  "FAILED",
	2:  "ENCODE_FAILED",
	3:  "DECODE_FAILED",
	4:  "SERVICE_EXCEPTION",
	10: "DATA_EXCEPTION",
	11: "INVALID_PARAMETER",
}

var CODE_value = map[string]int32{
	"OK":                0,
	"FAILED":            1,
	"ENCODE_FAILED":     2,
	"DECODE_FAILED":     3,
	"SERVICE_EXCEPTION": 4,
	"DATA_EXCEPTION":    10,
	"INVALID_PARAMETER": 11,
}

func (x CODE) String() string {
	return proto.EnumName(CODE_name, int32(x))
}

func (CODE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{0}
}

type Resp struct {
	Code                 int32    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Desc                 string   `protobuf:"bytes,2,opt,name=Desc,proto3" json:"Desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Resp) Reset()         { *m = Resp{} }
func (m *Resp) String() string { return proto.CompactTextString(m) }
func (*Resp) ProtoMessage()    {}
func (*Resp) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{0}
}

func (m *Resp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resp.Unmarshal(m, b)
}
func (m *Resp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resp.Marshal(b, m, deterministic)
}
func (m *Resp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resp.Merge(m, src)
}
func (m *Resp) XXX_Size() int {
	return xxx_messageInfo_Resp.Size(m)
}
func (m *Resp) XXX_DiscardUnknown() {
	xxx_messageInfo_Resp.DiscardUnknown(m)
}

var xxx_messageInfo_Resp proto.InternalMessageInfo

func (m *Resp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Resp) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func init() {
	proto.RegisterEnum("base.CODE", CODE_name, CODE_value)
	proto.RegisterType((*Resp)(nil), "base.Resp")
}

func init() { proto.RegisterFile("base.proto", fileDescriptor_db1b6b0986796150) }

var fileDescriptor_db1b6b0986796150 = []byte{
	// 182 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0xcf, 0xc1, 0x0a, 0x82, 0x40,
	0x10, 0xc6, 0xf1, 0xd6, 0x36, 0xa1, 0x89, 0x62, 0x1d, 0x08, 0x3c, 0x4a, 0x27, 0xe9, 0xe0, 0xa5,
	0x27, 0x58, 0x76, 0x27, 0x58, 0x32, 0x95, 0x4d, 0xa4, 0x9b, 0x64, 0xed, 0x59, 0xc9, 0x9e, 0xa0,
	0x27, 0x8f, 0x95, 0x0e, 0xde, 0xfe, 0xfc, 0x66, 0x2e, 0x1f, 0x40, 0xf7, 0x18, 0x5d, 0x36, 0xbc,
	0xfb, 0x4f, 0x8f, 0xdc, 0xf7, 0x21, 0x03, 0x6e, 0xdd, 0x38, 0x20, 0x02, 0x57, 0xfd, 0xcb, 0xc5,
	0x2c, 0x61, 0xe9, 0xca, 0x4e, 0xed, 0x4d, 0xbb, 0xf1, 0x19, 0x07, 0x09, 0x4b, 0xd7, 0x76, 0xea,
	0xe3, 0x97, 0x01, 0x57, 0xa5, 0x26, 0x0c, 0x21, 0x28, 0x2f, 0x62, 0x81, 0x00, 0xe1, 0x59, 0x9a,
	0x9c, 0xb4, 0x60, 0x18, 0xc1, 0x96, 0x0a, 0x7f, 0x6d, 0xff, 0x14, 0x78, 0xd2, 0x34, 0xa7, 0x25,
	0xee, 0x21, 0xba, 0x91, 0x6d, 0x8c, 0xa2, 0x96, 0xee, 0x8a, 0xaa, 0xda, 0x94, 0x85, 0xe0, 0x88,
	0xb0, 0xd3, 0xb2, 0x96, 0x33, 0x03, 0xff, 0x6a, 0x8a, 0x46, 0xe6, 0x46, 0xb7, 0x95, 0xb4, 0xf2,
	0x4a, 0x35, 0x59, 0xb1, 0xe9, 0xc2, 0x69, 0xc1, 0xe9, 0x17, 0x00, 0x00, 0xff, 0xff, 0x89, 0x8a,
	0x19, 0x4c, 0xcf, 0x00, 0x00, 0x00,
}
